### PR TITLE
add weekStart to settings

### PR DESCRIPTION
**Pull request by scherke**
Hello,
my week starts with Monday. I thought I implement it. Can you use it?

Day of the week start. 0 (Sunday) to 6 (Saturday)

### CODE REVIEW

**Comment by dgrubelic** [comment]
Please check out changes on settings object in this commit cdec94e0b52dfb3bba00a71f61a808709e14136e and apply to PR. I'll review it later today.

**Comment by scherke** [comment]
Hey there i checkout the changes.

**Comment by dgrubelic** [comment]
Please rebase latest changes and see my comment in your commit.

**Comment by scherke** [comment]
done

**Pull request merged**
